### ISSUE TITLE
Реструктуризация каталога Language

### ISSUE THREAD

**Issue by julbinb** [Rasie1/c-of-x#1]
Хорошо бы как-то категоризировать файлы в папке `Language`. Там уже можно утонуть, дальше будет только хуже. Рекомендую разложить по подкаталогам. Например, отдельный каталог для вспомогательных файлов парсера/синтаксических ошибок, отдельно каталог со стандартной библиотекой, отдельно каталог для AST (возможно, с подкаталогами).

**Comment by Rasie1** [comment]
Так, на самом деле, и есть - только в основном каталоге лежат все подклассы Expression'а (а их сложно разделить логически - каждый исполняет свою отдельную задачу. Позже их будет меньше, так как большинство из них можно выразить через другие уже внутри языка), а в отдельном лежит заготовка для нового парсера. Когда будут добавляться новые "компоненты" - будет удобно создавать новые каталоги.
